---
- name: install epel repo
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/epel-release-7-11.noarch.rpm
    state: present

- name: install nginx and remi-php73 repo
  yum:
    name:
      - nginx
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install php packages
  yum:
    name: "{{ php_packages }}"
    state: present
    enablerepo: remi-php73
